version: '3'
services:
  testsamlidp_idp:
    build: .
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://app.example.com
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://app.example.com/login/callback
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://app.example.com/logout
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8080:8080"
    - "8443:8443"
    volumes:
    - /Users/ali/canvasx/docker-test-saml-idp/config/simplesamlphp:/var/www/simplesamlphp/config
